// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using smartacfe.Data;

namespace smartacfe.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20190713035538_unique-index")]
    partial class uniqueindex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("smartacfe.Models.ACDevice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessKey");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired();

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<string>("SerialNumber")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("ACDevices");
                });

            modelBuilder.Entity("smartacfe.Models.ACDeviceReading", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ACDeviceID");

                    b.Property<decimal>("COLevel");

                    b.Property<string>("HealthStatus");

                    b.Property<decimal>("Humidity");

                    b.Property<DateTime>("LoggedDateTime");

                    b.Property<DateTime>("ReadingDateTime");

                    b.Property<decimal>("Temperature");

                    b.HasKey("ID");

                    b.HasIndex("ACDeviceID");

                    b.ToTable("AcDeviceReadings");
                });

            modelBuilder.Entity("smartacfe.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("smartacfe.Models.ACDeviceReading", b =>
                {
                    b.HasOne("smartacfe.Models.ACDevice", "ACDevice")
                        .WithMany("ACDeviceReading")
                        .HasForeignKey("ACDeviceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
